project = 'osinfo'

#Import Flags
Import('env flags_unittest libutf platform')

#Sources
if platform == 'win32':
	source = Split("""win32.c""")
elif platform == 'linux':
	source = Split("""linux.c""")

obj = []
if flags_unittest == '1':
    source += libutf
    obj = env.Program(source)
else:    
    obj = env.SharedObject(source)
Return('obj')
