#!/usr/bin/env python

Import('env')
env = env.Clone()

env.Prepend(CPPPATH = ['.'])

env.StaticLibrary('vamp-hostsdk', [
  'src/vamp-hostsdk/Files.cpp',
  'src/vamp-hostsdk/PluginBufferingAdapter.cpp',
  'src/vamp-hostsdk/PluginChannelAdapter.cpp',
  'src/vamp-hostsdk/PluginHostAdapter.cpp',
  'src/vamp-hostsdk/PluginInputDomainAdapter.cpp',
  'src/vamp-hostsdk/PluginLoader.cpp',
  'src/vamp-hostsdk/PluginSummarisingAdapter.cpp',
  'src/vamp-hostsdk/PluginWrapper.cpp',
  'src/vamp-hostsdk/RealTime.cpp'
])

env.StaticLibrary('vamp-sdk', [
  'src/vamp-sdk/PluginAdapter.cpp',
  'src/vamp-sdk/RealTime.cpp',
])
