tabWidth: 2
singleQuote: false

overrides:
  - files: "*.d.ts"
    options:
      printWidth: 180
      tabWidth: 4
      semi: true
      singleQuote: true
      trailingComma: all
      bracketSpacing: true
      useTabs: false
