#!/usr/bin/env python

Import('env')
env = env.Clone()

soundtouch_sources = [
  'AAFilter.cpp',
  'BPMDetect.cpp',
  'FIFOSampleBuffer.cpp',
  'FIRFilter.cpp',
  'InterpolateCubic.cpp',
  'InterpolateLinear.cpp',
  'InterpolateShannon.cpp',
  'PeakFinder.cpp',
  'RateTransposer.cpp',
  'SoundTouch.cpp',
  'TDStretch.cpp',
  # SoundTouch CPU optimizations are only for x86
  # architectures. SoundTouch automatically ignores these files
  # when it is not being built for an architecture that supports
  # them.
  'cpu_detect_x86.cpp',
  'mmx_optimized.cpp',
  'sse_optimized.cpp',
]

env.StaticLibrary(target='soundtouch', source=soundtouch_sources)
