project = 'fsinfo'

#Sources
source = Split("""fsinfo.c""")

#Import Flags
Import('env flags_unittest libutf')

obj = []
if flags_unittest == '1':
    source += libutf
    obj = env.Program(source)
else:    
    obj = env.SharedObject(source)
Return('obj')
