# FindXKB module for the vcpkg buildenv, which does not bundle Qt6's XKB config.
if(NOT TARGET XKB::XKB)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(xkbcommon IMPORTED_TARGET xkbcommon)
    if(xkbcommon_FOUND)
      add_library(XKB::XKB ALIAS PkgConfig::xkbcommon)
      set(XKB_FOUND TRUE)
      set(XKB_LIBRARY ${xkbcommon_LIBRARIES})
      set(XKB_INCLUDE_DIR ${xkbcommon_INCLUDE_DIRS})
      set(XKB_VERSION ${xkbcommon_VERSION})
    endif()
  endif()
endif()
if(NOT XKB_FOUND)
  find_path(XKB_INCLUDE_DIR xkbcommon/xkbcommon.h)
  find_library(XKB_LIBRARY xkbcommon)
  if(XKB_INCLUDE_DIR AND XKB_LIBRARY)
    set(XKB_FOUND TRUE)
  endif()
endif()
if(XKB_FOUND)
  if(NOT TARGET XKB::XKB)
    add_library(XKB::XKB UNKNOWN IMPORTED)
    set_target_properties(XKB::XKB PROPERTIES
      IMPORTED_LOCATION "${XKB_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${XKB_INCLUDE_DIR}"
    )
  endif()
endif()
mark_as_advanced(XKB_LIBRARY XKB_INCLUDE_DIR)