#pragma once

#include <QObject>
#include <memory>
#include <vector>

#include "analyzer/plugins/analyzerplugin.h"
#include "analyzer/plugins/buffering_utils.h"
#include "util/types.h"

class GetKeyMode;

namespace mixxx {

// Structure to hold analysis results for a specific tuning frequency
struct TuningAnalysisResult {
    int frequencyHz;
    int keyChangeCount;
    bool hasValidStart;
    KeyChangeList keys;

    TuningAnalysisResult()
            : frequencyHz(440),
              keyChangeCount(0),
              hasValidStart(false) {
    }
};

class AnalyzerQueenMaryKey : public AnalyzerKeyPlugin {
  public:
    static AnalyzerPluginInfo pluginInfo() {
        return AnalyzerPluginInfo(
                // Don't change this ID. It was auto generated by VAMP until
                // Mixxx 2.1 and we keep it for a compatible config.
                "qm-keydetector:2",
                QObject::tr("Queen Mary University London"),
                QObject::tr("Queen Mary Key Detector"),
                false);
    }

    AnalyzerQueenMaryKey();
    ~AnalyzerQueenMaryKey() override;

    AnalyzerPluginInfo info() const override {
        return pluginInfo();
    }

    bool initialize(mixxx::audio::SampleRate sampleRate) override;
    bool processSamples(const CSAMPLE* pIn, SINT iLen) override;
    bool finalize() override;

    KeyChangeList getKeyChanges() const override {
        return m_resultKeys;
    }

    // 432Hz detection support (legacy, kept for compatibility)
    bool is432Hz() const override {
        return m_detectedTuningFrequency == 432;
    }

    void setDetect432Hz(bool enabled) override {
        m_bDetect432Hz = enabled;
    }

    // Dynamic tuning frequency detection
    int getTuningFrequencyHz() const override {
        return m_detectedTuningFrequency;
    }

    void setTuningDetectionRange(int minFreq, int maxFreq, int stepFreq) override {
        m_tuningMinFreq = minFreq;
        m_tuningMaxFreq = maxFreq;
        m_tuningStepFreq = stepFreq;
    }

    void setDetectTuningFrequency(bool enabled) override {
        m_bDetectTuningFrequency = enabled;
    }

  private:
    // Helper structure for each frequency analyzer
    // Destructor defined in cpp file where GetKeyMode is complete
    struct FrequencyAnalyzer {
        std::unique_ptr<GetKeyMode> keyMode;
        DownmixAndOverlapHelper helper;
        size_t currentFrame;
        KeyChangeList resultKeys;
        mixxx::track::io::key::ChromaticKey prevKey;
        int frequencyHz;

        FrequencyAnalyzer();
        ~FrequencyAnalyzer();
        FrequencyAnalyzer(FrequencyAnalyzer&& other) noexcept;
        FrequencyAnalyzer& operator=(FrequencyAnalyzer&& other) noexcept;

        // Non-copyable due to unique_ptr
        FrequencyAnalyzer(const FrequencyAnalyzer&) = delete;
        FrequencyAnalyzer& operator=(const FrequencyAnalyzer&) = delete;
    };

    // Primary result storage
    KeyChangeList m_resultKeys;

    // Legacy 432Hz detection (for backwards compatibility)
    bool m_bDetect432Hz;

    // Dynamic tuning frequency detection
    bool m_bDetectTuningFrequency;
    int m_tuningMinFreq;
    int m_tuningMaxFreq;
    int m_tuningStepFreq;
    int m_detectedTuningFrequency;

    // Vector of analyzers for different frequencies
    std::vector<FrequencyAnalyzer> m_frequencyAnalyzers;

    // Sample rate for initialization
    mixxx::audio::SampleRate m_sampleRate;

    // Helper to find the best tuning frequency from analysis results
    int findBestTuningFrequency() const;
};

} // namespace mixxx
