#pragma once

#include <QObject>
#include <memory>

#include "analyzer/plugins/analyzerplugin.h"
#include "analyzer/plugins/buffering_utils.h"
#include "util/types.h"

class GetKeyMode;

namespace mixxx {

class AnalyzerQueenMaryKey : public AnalyzerKeyPlugin {
  public:
    static AnalyzerPluginInfo pluginInfo() {
        return AnalyzerPluginInfo(
                // Don't change this ID. It was auto generated by VAMP until
                // Mixxx 2.1 and we keep it for a compatible config.
                "qm-keydetector:2",
                QObject::tr("Queen Mary University London"),
                QObject::tr("Queen Mary Key Detector"),
                false);
    }

    AnalyzerQueenMaryKey();
    ~AnalyzerQueenMaryKey() override;

    AnalyzerPluginInfo info() const override {
        return pluginInfo();
    }

    bool initialize(mixxx::audio::SampleRate sampleRate) override;
    bool processSamples(const CSAMPLE* pIn, SINT iLen) override;
    bool finalize() override;

    KeyChangeList getKeyChanges() const override {
        return m_resultKeys;
    }

    // 432Hz detection support
    bool is432Hz() const override {
        return m_bIs432Hz;
    }

    void setDetect432Hz(bool enabled) override {
        m_bDetect432Hz = enabled;
    }

  private:
    // 440Hz analyzer
    std::unique_ptr<GetKeyMode> m_pKeyMode;
    DownmixAndOverlapHelper m_helper;
    size_t m_currentFrame;
    KeyChangeList m_resultKeys;
    mixxx::track::io::key::ChromaticKey m_prevKey;

    // 432Hz analyzer (used when 432Hz detection is enabled)
    std::unique_ptr<GetKeyMode> m_pKeyMode432;
    DownmixAndOverlapHelper m_helper432;
    size_t m_currentFrame432;
    KeyChangeList m_resultKeys432;
    mixxx::track::io::key::ChromaticKey m_prevKey432;

    // 432Hz detection settings
    bool m_bDetect432Hz;
    bool m_bIs432Hz;
};

} // namespace mixxx
