#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import SCons
import shutil

Import('build', 'flags')


# On Posix default SCons.LIBPREFIX = 'lib', on Windows default SCons.LIBPREFIX = ''

m4a_sources = [
	"soundsource.cpp", # required to subclass soundsource
	"soundsourcem4a.cpp",  # MP4/M4A Support
]


#Tell SCons to build the SoundSourceM4A plugin
#=========================
if int(flags['m4a']):
	SHLIBPREFIX='lib' #Makes the filename "libsoundsourcem4a" consistently across platforms to make our lives easier.
	if build.platform_is_windows:
		ssm4a_bin = build.env.SharedLibrary('soundsourcem4a', m4a_sources, LINKCOM  = [build.env['LINKCOM'], 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;1'])
	else:
		ssm4a_bin = build.env.SharedLibrary('soundsourcem4a', m4a_sources)

	#Pass this soundsourcem4a library object file back to the SConscript above us.
	Return("ssm4a_bin")
else:
	Return("")



