name: 🚀 Feature Request
description: |
  What feature would you like to see added to Mixxx?
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe describe your use-case, not yet supported and a possible solution.
    validations:
      required: true
