Import('env')
env = env.Clone()

# Add root and include folders
env.Prepend(CPPPATH = ['.', '../include'])

# Sources used by base library and library that includes main.
gtest_source = 'src/gtest-all.cc'

# gtest.lib to be used by most apps (if you have your own main
# function)
gtest = env.StaticLibrary(target='gtest', source=gtest_source)
