#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import SCons
import shutil

Import('build')

if int(build.flags['mediafoundation']):
    env = build.env.Clone()
    conf = Configure(env)
    env = conf.Finish()
    env["LINKFLAGS"].remove("/entry:mainCRTStartup")
    # TODO(rryan): Why do we do this?
    if build.machine_is_64bit:
        env["LINKFLAGS"].remove("/subsystem:windows,5.02")
    else:
        env["LINKFLAGS"].remove("/subsystem:windows,5.01")
    ssmediafoundation_bin = env.SharedLibrary('soundsourcemediafoundation',
        ['soundsource.cpp', 'soundsourcetaglib.cpp', 'soundsourcemediafoundation.cpp'],
        LINKCOM  = [env['LINKCOM'],
            'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;1'])
    Return("ssmediafoundation_bin")
else:
    Return("")