Import('env')
env = env.Clone()

# Add root and include folders
env.Prepend(CPPPATH = ['.', '../include', '../../googletest/include'])

# Sources used by base library and library that includes main.
gmock_source = 'src/gmock-all.cc'

# gmock.lib to be used by most apps (if you have your own main
# function)
gmock = env.StaticLibrary(target='gmock', source=gmock_source)
