// Custom Action DLL to find Mixxx installations regardless of install scope.
// The standard MSI FindRelatedProducts skips per-user installs when the
// current install is per-machine. This includes the mismatch generated by
// CPACK_WIX_INSTALL_SCOPE "none".
// This MsiEnumRelatedProducts() has no such filter.

// clang-format off
// windows.h must precede msi.h (defines UINT, WINAPI, etc.)
#include <windows.h>
#include <msi.h>
#include <msiquery.h>
// clang-format on

#pragma comment(lib, "msi.lib")

// Mixxx Upgrade GUID — must match CPACK_WIX_UPGRADE_GUID
static const wchar_t kUpgradeCode[] = L"{921DC99C-4DCF-478D-B950-50685CB9E6BE}";

extern "C"
        __declspec(dllexport) UINT __stdcall FindAllRelatedMixxxInstallations(
                MSIHANDLE hInstall) {
    // Get our own ProductCode so we don't mark ourselves for removal.
    wchar_t productCode[39] = {};
    DWORD productCodeLen = 39;
    MsiGetPropertyW(hInstall, L"ProductCode", productCode, &productCodeLen);

    // Enumerate ALL products with our UpgradeCode (scope-agnostic).
    wchar_t relatedProduct[39] = {};
    DWORD index = 0;
    while (MsiEnumRelatedProductsW(kUpgradeCode, 0, index, relatedProduct) == ERROR_SUCCESS) {
        if (wcscmp(relatedProduct, productCode) != 0) {
            // Found an older/different installation — mark it for upgrade removal.
            MsiSetPropertyW(hInstall, L"WIX_UPGRADE_DETECTED", relatedProduct);
            MsiSetPropertyW(hInstall, L"MIGRATE", relatedProduct);
            MsiSetPropertyW(hInstall, L"UPGRADINGPRODUCTCODE", relatedProduct);
            break; // Typically only one old installation exists
        }
        ++index;
    }

    return ERROR_SUCCESS;
}
