#!/usr/bin/env python3
"""
Small qmllint wrapper that finds the Qt tool and sets up the import paths.

The `Mixxx` and `Mixxx.Controls` QML modules are backed by C++ types, and
their `qmldir`/`qmltypes` files are generated by the build. Without them
qmllint cannot resolve `Mixxx.ControlProxy` & co. and every file that
imports Mixxx drowns in "not found" warnings. This wrapper adds the QML
output directory of the CMake build (``build/`` or ``$MIXXX_BUILD_DIR``)
to qmllint's import paths, so the results are meaningful.

All other arguments are passed through to qmllint unchanged.
"""

import sys

from qmlformat import find_build_dir, require_qt_tool, run_qt_tool

NO_BUILD_MESSAGE = """
qmllint: no configured CMake build directory found (looked for build/,
build*/, cmake_build*/ or $MIXXX_BUILD_DIR containing CMakeCache.txt).
The C++ backed types of the Mixxx QML module are only known to qmllint
through the qmltypes files the build generates, so expect import
warnings for `import Mixxx` until you configure and build Mixxx.
"""

NOT_BUILT_MESSAGE = """
qmllint: {qml_dir} does not exist yet. The Mixxx QML module's qmldir and
qmltypes are generated by the build, so build Mixxx (or at least the
`all_qmltyperegistrations` target) before linting.
"""


def import_path_args():
    build_dir = find_build_dir()
    if build_dir is None:
        print(NO_BUILD_MESSAGE.strip(), file=sys.stderr)
        return []
    qml_dir = build_dir / "qml"
    if not (qml_dir / "Mixxx" / "qmldir").is_file():
        print(
            NOT_BUILT_MESSAGE.format(qml_dir=qml_dir).strip(), file=sys.stderr
        )
        return []
    return ["-I", str(qml_dir)]


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    executable = require_qt_tool("qmllint")
    # -E additionally honours QML_IMPORT_PATH, like the running application.
    command = [executable, "-E"] + import_path_args() + list(argv)
    return run_qt_tool(command)


if __name__ == "__main__":
    sys.exit(main())
