#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, os, platform

architecture = platform.architecture()
machine = platform.machine()
Export('machine')	#So architecture-specific decisions & optimizations can be made in the SConscript
Export('architecture')

if os.name == 'nt':
	print 'Platform: Windows' + machine + ' (' + architecture[0] + ')'
	if machine == 'x86':
		platform = 'win32'
	else:		#This is only correctly detected if you're running a 64-bit version of Python, otherwise it'll see an x86 system
		platform = 'win64'
	
	# Allow to override auto-detection (environment variables must already be set appropriately with SETENV.CMD /xp /x86 or /x64)
	if ARGUMENTS.get('win64'):
		print 'FORCING 64-BIT BUILD'
		platform = 'win64'
	if ARGUMENTS.get('win32'):
		print 'FORCING 32-BIT BUILD'
		platform = 'win32'
	
elif sys.platform == 'linux2':
     print 'Platform: Linux ' + machine + ' (' + architecture[0] + ')'
     platform = 'linux'
elif 'bsd' in sys.platform: #should cover {Net,Open,Free,DragonFly}BSD, but I'll be upfront: I've only built Mixxx on OpenBSD
     print 'Platform: BSD ' + machine + ' (' + architecture[0] + ')'
     platform = 'bsd'
elif sys.platform == 'darwin':
     print 'Platform: OS X ' + machine + ' (' + architecture[0] + ')'
     platform = 'osx'
else:
	print 'Platform: Unknown (assuming Linux-like,) ' + machine + ' (' + architecture[0] + ')'
	platform = 'linux'

print 'Binary format: ' + architecture[1]

build_dir = '%s_build' % platform

Export('platform')
Export('build_dir')

SConscript(File('src/SConscript'), build_dir=Dir(build_dir), duplicate=0) 
SConscript(File('plugins/SConscript'), build_dir=Dir(build_dir + "/plugins"), duplicate=0) 
#wtf doesn't this work on win32 (works on Linux, OS X):
Command("mixxx", os.path.join(build_dir, "mixxx"), Copy("$TARGET", "$SOURCE"))

#hack for windows:
Copy("mixxx", os.path.join(build_dir, "mixxx"))

#on OS X, if the bundle has been built, copy it up:
#Command("Mixxx.app", os.path.join(build_dir, "Mixxx.app"), Copy("$TARGET", "$SOURCE"))
