#!/usr/bin/env python
# -*- coding: utf-8 -*-

Import('build_dir')

plugins = [] 
soundsourcem4a = SConscript(File('soundsourcem4a/SConscript'), build_dir=Dir(build_dir), duplicate=0) 
plugins.append(soundsourcem4a)

Return("plugins")
