# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Changelog

on:
  push:
    branches:
      - "main"
      - "[0-9].[0-9]"
    paths:
      - "CHANGELOG.md"

permissions: {}
jobs:
  trigger-changelog-update:
    name: Trigger Changelog update on manual repository
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch name
        uses: nelonoel/branch-name@1ea5c86cb559a8c4e623da7f188496208232e49f
      - name: Start workflow run on manual repository
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0
        if: env.MIXXXBOT_TOKEN != null
        with:
          token: ${{ env.MIXXXBOT_TOKEN }}
          repository: mixxxdj/manual
          event-type: update-changelog
          client-payload: '{"branch": "${{ env.BRANCH_NAME }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        env:
          MIXXXBOT_TOKEN: ${{ secrets.MIXXXBOT_CHANGELOG_AUTOUPDATER_PAT }}
