name: Pull request or branch build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  push:
    branches:
      - "*"
      - "!main"
      - "![0-9].[0-9]"
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)
  checks: write #  to create new checks (coverallsapp/github-action)
  actions: read #  to list the UI test artifacts (ready)

jobs:
  stop-build:
    name: Check if build should be stopped
    runs-on: ubuntu-latest
    outputs:
      result: ${{ github.event_name == 'push' && steps.stop-build.outputs.result || 'false' }}
    steps:
      - name: Check if there is an open PR for this branch
        id: stop-build
        if: ${{ github.event_name == 'push' }}
        uses: actions/github-script@v8
        env:
          ORGANIZATION: mixxxdj
          REPOSITORY: mixxx
        with:
          script: |
            try {
              const branch = context.ref.replace('refs/heads/', '');
              const { data: pullRequests } = await github.rest.pulls.list({
                owner: process.env.ORGANIZATION,
                repo: process.env.REPOSITORY,
                head: `${context.repo.owner}:${branch}`,
                state: 'open'
              });
              console.log(`There is ${pullRequests.length} PR open upstream for branch '${context.repo.owner}:${branch}'`);
              return pullRequests.length != 0;
            } catch (error) {
              console.log(`Didn't find a PR for branch '${context.repo.owner}:${branch}' on '${process.env.ORGANIZATION}/${process.env.REPOSITORY}'.`);
              return false;
            }

  pre-commit:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/pre-commit.yml
    with:
      pull_request: ${{ github.event_name == 'pull_request' }}

  checks:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/checks.yml

  git:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/git.yml

  build:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      ref: ${{ github.ref }}

  # This task is used as a probe for auto merge
  # In the future, it could also be used to perform a status update (e.g once the whole CI is passing + is ready for review, add a specific label such as `need review`)
  ready:
    name: Ready to merge
    needs:
      - pre-commit
      - checks
      - git
      - build
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'pull_request'
    steps:
      - name: Fetch all UI results artifacts
        id: generateCommentBody
        run: |
          commentBody=""
          for result in `gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq '.artifacts[] | select(.name | test("^UI Tests for")) | .name + "|" + .url' -r`; do
            label=$(echo $result | cut -d'|' -f 1)
            outcome=$(echo $result | rev | awk '{print $1}' | rev)
            label=$(echo $label | cut -d'-' -f 1)
            url=$(echo $result | cut -d'|' -f 2)
            if [ "$outcome" = "failure" ]; then
              commentBody="$commentBody- :x: $label - ([view results]($url))\n"
            else
              commentBody="$commentBody- :white_check_mark: $label - ([view results]($url))\n"
            fi
          done
          echo "comment-body=${commentBody}" >> "${GITHUB_OUTPUT}"
          cat "${GITHUB_OUTPUT}"

      - name: "[UI tests] Find existing comment"
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        id: find-tests-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "## QML UI test results"

      - name: "[UI tests] Update existing comment or create a new one"
        uses: peter-evans/create-or-update-comment@fffe59ea229327e73edca9d31f0b578bf04152a9
        if: steps.generateCommentBody.outputs.commentBody != ''
        with:
          comment-id: ${{ steps.find-tests-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## QML UI test results

            ${{ steps.generateCommentBody.outputs.comment-body }}
          edit-mode: replace

      - name: Ready to go
        id: ready
        if: needs.pre-commit.outcome == 'success' && needs.checks.outcome == 'success' && needs.git.outcome == 'success' && needs.build.outcome == 'success'
        run: "exit 0"

      - name: Not ready
        if: steps.ready.outcome == 'skipped'
        run: "exit 1"
