name: Git Checks

on:
  workflow_call:

jobs:
  block-fixup:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v7
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v2.0.0
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
