name: "NixOS dev build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
        path: .ccache
        key: ${ { matrix.config.name } }-ccache-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
        restore-keys: |
            ${ { matrix.config.name } }-ccache-
    - name: cache nix store
      uses: actions/cache@v1.1.0
      with:
        path: /nix/store
        key: ${ { matrix.config.name } }-nix-store
        restore-keys: |
            ${ { matrix.config.name } }-nix-store
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-shell --arg enableKeyfinder true --arg defaultLv2Plugins true --command "configure && build && run-tests"
