name: "NixOS dev build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-shell --arg enableKeyfinder true --arg defaultLv2Plugins true --command "configure && build && run-tests"
