name: Softfix workflow
on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  softfix:
    name: Softfix action
    if: github.event.issue.pull_request != '' && startsWith(github.event.comment.body, '/softfix')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check if commenter is maintainer
        id: check-maintainer
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const response = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.comment.user.login
            });

            const isMaintainer = ['admin', 'write'].includes(response.data.permission);
            return isMaintainer;
      - name: Checkout repository
        if: steps.check-maintainer.outputs.result == 'true'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Softfix
        if: steps.check-maintainer.outputs.result == 'true'
        uses: daschuer/softfix@807aa583c81496801cc5892b0ab43d4aba70e1f0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
